from setuptools import find_packages, setup

setup(
    name='movecar2',
    version='0.1.0',
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    install_requires=[
        'blinker==1.6.2',
        'certifi==2023.5.7',
        'charset-normalizer==3.1.0',
        'click==8.1.3',
        'Flask==2.3.2',
        'gitdb==4.0.10',
        'GitPython==3.1.32',
        'idna==3.4',
        'itsdangerous==2.1.2',
        'Jinja2==3.1.2',
        'MarkupSafe==2.1.3',
        'python-dotenv==1.0.0',
        'requests==2.31.0',
        'smmap==5.0.0',
        'urllib3==2.0.3',
        'Werkzeug==2.3.6'],
    data=[
        'data/parsed_hobokken_rules',
        'data/test_file',
        'data/weather_forecast'
    ],
    data_raw=[
        'data_raw/current_hoboken_rules_output',
        'data_raw/new_hoboken_rules_output'
              ],
    scripts=[
        'scripts/clean_rules_data_script',
        'scripts/scrape_website_hoboken',
        'scripts/weather_script',
        'scripts/test_script'])
